### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Keesromkes**
Link to developers.homebridge.io didn't work correctly (lacked protocol)

### CODE REVIEW

**Comment by ztalbot2000** [comment]
Hi, Thanks,

  I've had such difficulty proofing .md files. Atom is my latest attempt.  If you know of anything better that works on a Mac, or even a Pi, please let me know.

ttfn,
John Talbot

**Comment by Keesromkes** [comment]
@ztalbot2000 I'm not aware of how to do that sorry - I only found this issue when trying to click on it 😉 Maybe you could search for each link between () and add the protocol in front of it? https is a pretty safe bet

**Comment by ztalbot2000** [comment]
Hi,

  My problem is that when I want to create a link in my Md files, it is not
really until they are on GitHub can I actually test them fully. Many times
I've resubmitted only to find they are still broken.  At some point I give
up.  I'm very happy that you were able to fix the one you found.  It is
much appreciated.

John

**Comment by Keesromkes** [comment]
I'm happy to help John! And I get your point, running tests on a MD file is a bit eh, too much effort for the benefits!

I'll go through your initial MD to see what I can find, and will do a PR to update - I have some time on my hands and am happy to help your work move further!

**Pull request merged**
